version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: user_backend
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env/.env.dev
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - user_app_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  user_app_data:
